name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * 0' # Chạy mỗi tuần một lần
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          # Checkout nhánh builds-2 của repo fork
          ref: builds-2

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream repository
        run: git remote add upstream https://github.com/stealer-smile/extension.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Checkout upstream builds-2
        run: git checkout -B builds-2 upstream/builds-2

      - name: Merge upstream changes into local builds-2
        run: |
          git checkout builds-2
          git merge upstream/builds-2 --ff-only || echo "No changes to merge"

      - name: Push changes to fork builds-2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Sử dụng token để đẩy code lên repository fork
        run: git push origin builds-2
